# Generated by Django 3.0.6 on 2020-08-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PROJECT_CREATED', 'PROJECT_CREATED'), ('PROJECT_TRAINING', 'PROJECT_TRAINING'), ('PROJECT_COMPLETED', 'PROJECT_COMPLETED')], default='PROJECT_CREATED', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('saved_model_path', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('MODEL_CREATED', 'MODEL_CREATED'), ('MODEL_TRAINING', 'MODEL_TRAINING'), ('MODEL_COMPLETED', 'MODEL_COMPLETED')], default='PROJECT_CREATED', max_length=60)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiml.Project')),
            ],
        ),
    ]
