# Generated by Django 3.0.6 on 2020-08-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='saved_model_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
