# Generated by Django 3.0.6 on 2020-08-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0002_auto_20200815_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='status',
            field=models.CharField(choices=[('MODEL_CREATED', 'MODEL_CREATED'), ('MODEL_TRAINING', 'MODEL_TRAINING'), ('MODEL_COMPLETED', 'MODEL_COMPLETED'), ('MODEL_ERROR', 'MODEL_ERROR')], default='PROJECT_CREATED', max_length=60),
        ),
    ]
