# Generated by Django 3.0.6 on 2020-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0003_auto_20200815_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
