# Generated by Django 3.0.6 on 2020-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0004_auto_20200816_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='rtwo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='type',
            field=models.CharField(choices=[('STATS_CLASSIFICATION', 'STATS_CLASSIFICATION'), ('STATS_REGRESSION', 'STATS_REGRESSION')], default='STATS_CLASSIFICATION', max_length=60),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
