# Generated by Django 3.0.6 on 2020-08-16 11:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0005_auto_20200816_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='rtwo_score',
        ),
        migrations.AddField(
            model_name='statistics',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
