# Generated by Django 3.0.6 on 2020-08-16 11:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0006_auto_20200816_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
