# Generated by Django 3.0.6 on 2020-08-16 13:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiml', '0007_auto_20200816_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.AddField(
            model_name='model',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.CharField(choices=[('classification', 'classification'), ('regression', 'regression')], default='classification', max_length=60),
        ),
    ]
